services:
  leafylog-web:
    build: .
    container_name: leafylog-web
    restart: unless-stopped
    networks:
      - proxy_net

networks:
  proxy_net:
    external: true
    name: myproject_default
